//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Balance Sweeping Event.
 * 
 * <p>Java class for DailyTransfer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DailyTransfer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="TimeTransfer" type="{urn:cbr-ru:ed:leaftypes:v2.0}TimeType"/&gt;
 *         &lt;element name="EventTransfer" type="{urn:cbr-ru:ed:v2.0}EventTransfer"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DailyTransfer", propOrder = {
    "eventTransfer",
    "timeTransfer"
})
public class DailyTransfer
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "EventTransfer")
    protected EventTransfer eventTransfer;
    @XmlElement(name = "TimeTransfer")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar timeTransfer;

    /**
     * Gets the value of the eventTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link EventTransfer }
     *     
     */
    public EventTransfer getEventTransfer() {
        return eventTransfer;
    }

    /**
     * Sets the value of the eventTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTransfer }
     *     
     */
    public void setEventTransfer(EventTransfer value) {
        this.eventTransfer = value;
    }

    /**
     * Gets the value of the timeTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeTransfer() {
        return timeTransfer;
    }

    /**
     * Sets the value of the timeTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeTransfer(XMLGregorianCalendar value) {
        this.timeTransfer = value;
    }

}
