//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;
import ru.cbr.ed.leaftypes.v2.ReasonCodeType;
import ru.cbr.ed.leaftypes.v2.RequestCodeType;


/**
 * Full National BIC Directory/ National BIC Directory Changes
 * 
 * <p>Java class for ED807 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ED807"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:cbr-ru:ed:v2.0}ESIDWithPartInfo"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BICDirectoryEntry" type="{urn:cbr-ru:ed:v2.0}BICDirectoryEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CreationReason" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}ReasonCodeType" /&gt;
 *       &lt;attribute name="CreationDateTime" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}DateTimeType" /&gt;
 *       &lt;attribute name="InfoTypeCode" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}RequestCodeType" /&gt;
 *       &lt;attribute name="BusinessDay" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}DateType" /&gt;
 *       &lt;attribute name="DirectoryVersion" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max2NumberType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ED807", propOrder = {
    "bicDirectoryEntries"
})
@XmlRootElement(name = "ED807")
public class ED807
    extends ESIDWithPartInfo
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "BICDirectoryEntry")
    protected List<BICDirectoryEntryType> bicDirectoryEntries;
    @XmlAttribute(name = "CreationReason", required = true)
    protected ReasonCodeType creationReason;
    @XmlAttribute(name = "CreationDateTime", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Calendar creationDateTime;
    @XmlAttribute(name = "InfoTypeCode", required = true)
    protected RequestCodeType infoTypeCode;
    @XmlAttribute(name = "BusinessDay", required = true)
    protected XMLGregorianCalendar businessDay;
    @XmlAttribute(name = "DirectoryVersion")
    protected BigInteger directoryVersion;

    /**
     * Gets the value of the bicDirectoryEntries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the bicDirectoryEntries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBICDirectoryEntries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BICDirectoryEntryType }
     * 
     * 
     */
    public List<BICDirectoryEntryType> getBICDirectoryEntries() {
        if (bicDirectoryEntries == null) {
            bicDirectoryEntries = new ArrayList<BICDirectoryEntryType>();
        }
        return this.bicDirectoryEntries;
    }

    /**
     * Gets the value of the creationReason property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonCodeType }
     *     
     */
    public ReasonCodeType getCreationReason() {
        return creationReason;
    }

    /**
     * Sets the value of the creationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonCodeType }
     *     
     */
    public void setCreationReason(ReasonCodeType value) {
        this.creationReason = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDateTime(Calendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the infoTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link RequestCodeType }
     *     
     */
    public RequestCodeType getInfoTypeCode() {
        return infoTypeCode;
    }

    /**
     * Sets the value of the infoTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestCodeType }
     *     
     */
    public void setInfoTypeCode(RequestCodeType value) {
        this.infoTypeCode = value;
    }

    /**
     * Gets the value of the businessDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBusinessDay() {
        return businessDay;
    }

    /**
     * Sets the value of the businessDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBusinessDay(XMLGregorianCalendar value) {
        this.businessDay = value;
    }

    /**
     * Gets the value of the directoryVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDirectoryVersion() {
        return directoryVersion;
    }

    /**
     * Sets the value of the directoryVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDirectoryVersion(BigInteger value) {
        this.directoryVersion = value;
    }

}
