//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Общие реквизиты служебно-информационного пакета для ЭКО
 * 
 * <p>Java class for ESIDResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESIDResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:cbr-ru:ed:v2.0}ESID"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InitialEDInfo" type="{urn:cbr-ru:ed:v2.0}InitialEDInfo" minOccurs="0"/&gt;
 *         &lt;element name="InitialED" type="{urn:cbr-ru:ed:v2.0}EDRefID" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESIDResponse", propOrder = {
    "initialEDInfo",
    "initialED"
})
public class ESIDResponse
    extends ESID
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "InitialEDInfo")
    protected InitialEDInfo initialEDInfo;
    @XmlElement(name = "InitialED")
    protected EDRefID initialED;

    /**
     * Gets the value of the initialEDInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InitialEDInfo }
     *     
     */
    public InitialEDInfo getInitialEDInfo() {
        return initialEDInfo;
    }

    /**
     * Sets the value of the initialEDInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialEDInfo }
     *     
     */
    public void setInitialEDInfo(InitialEDInfo value) {
        this.initialEDInfo = value;
    }

    /**
     * Gets the value of the initialED property.
     * 
     * @return
     *     possible object is
     *     {@link EDRefID }
     *     
     */
    public EDRefID getInitialED() {
        return initialED;
    }

    /**
     * Sets the value of the initialED property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDRefID }
     *     
     */
    public void setInitialED(EDRefID value) {
        this.initialED = value;
    }

}
