//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Информация о косвенном участнике.
 * 
 * <p>Java class for IndirectParticipantInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndirectParticipantInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="IPBICPayer" type="{urn:cbr-ru:ed:leaftypes:v2.0}BICRUIDType" /&gt;
 *       &lt;attribute name="IPBICPayee" type="{urn:cbr-ru:ed:leaftypes:v2.0}BICRUIDType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndirectParticipantInfoType")
public class IndirectParticipantInfoType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "IPBICPayer")
    protected String ipbicPayer;
    @XmlAttribute(name = "IPBICPayee")
    protected String ipbicPayee;

    /**
     * Gets the value of the ipbicPayer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPBICPayer() {
        return ipbicPayer;
    }

    /**
     * Sets the value of the ipbicPayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPBICPayer(String value) {
        this.ipbicPayer = value;
    }

    /**
     * Gets the value of the ipbicPayee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPBICPayee() {
        return ipbicPayee;
    }

    /**
     * Sets the value of the ipbicPayee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPBICPayee(String value) {
        this.ipbicPayee = value;
    }

}
