//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import ru.cbr.ed.leaftypes.v2.RstrType;


/**
 * Indirect Participant's Restrictions.
 * 
 * <p>Java class for IPRstrListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPRstrListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="IPRstr" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}RstrType" /&gt;
 *       &lt;attribute name="RstrDate" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}DateType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPRstrListType")
public class IPRstrListType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "IPRstr", required = true)
    protected RstrType ipRstr;
    @XmlAttribute(name = "RstrDate", required = true)
    protected XMLGregorianCalendar rstrDate;

    /**
     * Gets the value of the ipRstr property.
     * 
     * @return
     *     possible object is
     *     {@link RstrType }
     *     
     */
    public RstrType getIPRstr() {
        return ipRstr;
    }

    /**
     * Sets the value of the ipRstr property.
     * 
     * @param value
     *     allowed object is
     *     {@link RstrType }
     *     
     */
    public void setIPRstr(RstrType value) {
        this.ipRstr = value;
    }

    /**
     * Gets the value of the rstrDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRstrDate() {
        return rstrDate;
    }

    /**
     * Sets the value of the rstrDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRstrDate(XMLGregorianCalendar value) {
        this.rstrDate = value;
    }

}
