//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import ru.cbr.ed.leaftypes.v2.Me2MeType;
import ru.cbr.ed.leaftypes.v2.PaymentCategoryType;


/**
 * Информация о переводе денежных средств физическим лицом между своими счетами.
 * 
 * <p>Java class for Me2MeDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Me2MeDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Me2Me" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Me2MeType" /&gt;
 *       &lt;attribute name="PaymentCategory" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}PaymentCategoryType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Me2MeDetailsType")
public class Me2MeDetailsType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "Me2Me", required = true)
    protected Me2MeType me2Me;
    @XmlAttribute(name = "PaymentCategory", required = true)
    protected PaymentCategoryType paymentCategory;

    /**
     * Gets the value of the me2Me property.
     * 
     * @return
     *     possible object is
     *     {@link Me2MeType }
     *     
     */
    public Me2MeType getMe2Me() {
        return me2Me;
    }

    /**
     * Sets the value of the me2Me property.
     * 
     * @param value
     *     allowed object is
     *     {@link Me2MeType }
     *     
     */
    public void setMe2Me(Me2MeType value) {
        this.me2Me = value;
    }

    /**
     * Gets the value of the paymentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCategoryType }
     *     
     */
    public PaymentCategoryType getPaymentCategory() {
        return paymentCategory;
    }

    /**
     * Sets the value of the paymentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCategoryType }
     *     
     */
    public void setPaymentCategory(PaymentCategoryType value) {
        this.paymentCategory = value;
    }

}
