//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.cbr.ed.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.cbr.ed.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ED807 }
     * 
     */
    public ED807 createED807() {
        return new ED807();
    }

    /**
     * Create an instance of {@link ESIDWithPartInfo }
     * 
     */
    public ESIDWithPartInfo createESIDWithPartInfo() {
        return new ESIDWithPartInfo();
    }

    /**
     * Create an instance of {@link ESID }
     * 
     */
    public ESID createESID() {
        return new ESID();
    }

    /**
     * Create an instance of {@link ED }
     * 
     */
    public ED createED() {
        return new ED();
    }

    /**
     * Create an instance of {@link EDRefID }
     * 
     */
    public EDRefID createEDRefID() {
        return new EDRefID();
    }

    /**
     * Create an instance of {@link PartInfo }
     * 
     */
    public PartInfo createPartInfo() {
        return new PartInfo();
    }

    /**
     * Create an instance of {@link BICDirectoryEntryType }
     * 
     */
    public BICDirectoryEntryType createBICDirectoryEntryType() {
        return new BICDirectoryEntryType();
    }

    /**
     * Create an instance of {@link AccDocRefID }
     * 
     */
    public AccDocRefID createAccDocRefID() {
        return new AccDocRefID();
    }

    /**
     * Create an instance of {@link AccModifList }
     * 
     */
    public AccModifList createAccModifList() {
        return new AccModifList();
    }

    /**
     * Create an instance of {@link AccBrfModifList }
     * 
     */
    public AccBrfModifList createAccBrfModifList() {
        return new AccBrfModifList();
    }

    /**
     * Create an instance of {@link AccIntradayRestrictions }
     * 
     */
    public AccIntradayRestrictions createAccIntradayRestrictions() {
        return new AccIntradayRestrictions();
    }

    /**
     * Create an instance of {@link AccMigrated }
     * 
     */
    public AccMigrated createAccMigrated() {
        return new AccMigrated();
    }

    /**
     * Create an instance of {@link AccOI }
     * 
     */
    public AccOI createAccOI() {
        return new AccOI();
    }

    /**
     * Create an instance of {@link AccountsInfoType }
     * 
     */
    public AccountsInfoType createAccountsInfoType() {
        return new AccountsInfoType();
    }

    /**
     * Create an instance of {@link AccRstrListType }
     * 
     */
    public AccRstrListType createAccRstrListType() {
        return new AccRstrListType();
    }

    /**
     * Create an instance of {@link AccountsType }
     * 
     */
    public AccountsType createAccountsType() {
        return new AccountsType();
    }

    /**
     * Create an instance of {@link AdditionalConditions }
     * 
     */
    public AdditionalConditions createAdditionalConditions() {
        return new AdditionalConditions();
    }

    /**
     * Create an instance of {@link ArrestDetailedInfo }
     * 
     */
    public ArrestDetailedInfo createArrestDetailedInfo() {
        return new ArrestDetailedInfo();
    }

    /**
     * Create an instance of {@link ArrestInfo }
     * 
     */
    public ArrestInfo createArrestInfo() {
        return new ArrestInfo();
    }

    /**
     * Create an instance of {@link ArrestsInfo }
     * 
     */
    public ArrestsInfo createArrestsInfo() {
        return new ArrestsInfo();
    }

    /**
     * Create an instance of {@link AuthClaimAuthorType }
     * 
     */
    public AuthClaimAuthorType createAuthClaimAuthorType() {
        return new AuthClaimAuthorType();
    }

    /**
     * Create an instance of {@link AuthorizedClaimAuthors }
     * 
     */
    public AuthorizedClaimAuthors createAuthorizedClaimAuthors() {
        return new AuthorizedClaimAuthors();
    }

    /**
     * Create an instance of {@link AuthorizedClaimAuthorsList }
     * 
     */
    public AuthorizedClaimAuthorsList createAuthorizedClaimAuthorsList() {
        return new AuthorizedClaimAuthorsList();
    }

    /**
     * Create an instance of {@link AuthorizedClaimAuthorsForIP }
     * 
     */
    public AuthorizedClaimAuthorsForIP createAuthorizedClaimAuthorsForIP() {
        return new AuthorizedClaimAuthorsForIP();
    }

    /**
     * Create an instance of {@link AuthorizedClaimAuthorsListForIP }
     * 
     */
    public AuthorizedClaimAuthorsListForIP createAuthorizedClaimAuthorsListForIP() {
        return new AuthorizedClaimAuthorsListForIP();
    }

    /**
     * Create an instance of {@link BankRU }
     * 
     */
    public BankRU createBankRU() {
        return new BankRU();
    }

    /**
     * Create an instance of {@link BICAccCSListType }
     * 
     */
    public BICAccCSListType createBICAccCSListType() {
        return new BICAccCSListType();
    }

    /**
     * Create an instance of {@link BICDirectoryEntryExt }
     * 
     */
    public BICDirectoryEntryExt createBICDirectoryEntryExt() {
        return new BICDirectoryEntryExt();
    }

    /**
     * Create an instance of {@link BICInfo }
     * 
     */
    public BICInfo createBICInfo() {
        return new BICInfo();
    }

    /**
     * Create an instance of {@link Cash }
     * 
     */
    public Cash createCash() {
        return new Cash();
    }

    /**
     * Create an instance of {@link CashAccInfo }
     * 
     */
    public CashAccInfo createCashAccInfo() {
        return new CashAccInfo();
    }

    /**
     * Create an instance of {@link CashCorrespondentInfo }
     * 
     */
    public CashCorrespondentInfo createCashCorrespondentInfo() {
        return new CashCorrespondentInfo();
    }

    /**
     * Create an instance of {@link CFBICList }
     * 
     */
    public CFBICList createCFBICList() {
        return new CFBICList();
    }

    /**
     * Create an instance of {@link ClearingAccount }
     * 
     */
    public ClearingAccount createClearingAccount() {
        return new ClearingAccount();
    }

    /**
     * Create an instance of {@link ClearingCircuits }
     * 
     */
    public ClearingCircuits createClearingCircuits() {
        return new ClearingCircuits();
    }

    /**
     * Create an instance of {@link CoverFundsSchemeParameters }
     * 
     */
    public CoverFundsSchemeParameters createCoverFundsSchemeParameters() {
        return new CoverFundsSchemeParameters();
    }

    /**
     * Create an instance of {@link CoverSum }
     * 
     */
    public CoverSum createCoverSum() {
        return new CoverSum();
    }

    /**
     * Create an instance of {@link CustomerAccInfo }
     * 
     */
    public CustomerAccInfo createCustomerAccInfo() {
        return new CustomerAccInfo();
    }

    /**
     * Create an instance of {@link CustomerMemoOrder }
     * 
     */
    public CustomerMemoOrder createCustomerMemoOrder() {
        return new CustomerMemoOrder();
    }

    /**
     * Create an instance of {@link DailyTransfer }
     * 
     */
    public DailyTransfer createDailyTransfer() {
        return new DailyTransfer();
    }

    /**
     * Create an instance of {@link DepartmentalInfo }
     * 
     */
    public DepartmentalInfo createDepartmentalInfo() {
        return new DepartmentalInfo();
    }

    /**
     * Create an instance of {@link DataForm }
     * 
     */
    public DataForm createDataForm() {
        return new DataForm();
    }

    /**
     * Create an instance of {@link DepositInfo }
     * 
     */
    public DepositInfo createDepositInfo() {
        return new DepositInfo();
    }

    /**
     * Create an instance of {@link DestinationInfo }
     * 
     */
    public DestinationInfo createDestinationInfo() {
        return new DestinationInfo();
    }

    /**
     * Create an instance of {@link EPDComplete }
     * 
     */
    public EPDComplete createEPDComplete() {
        return new EPDComplete();
    }

    /**
     * Create an instance of {@link EPSInfo }
     * 
     */
    public EPSInfo createEPSInfo() {
        return new EPSInfo();
    }

    /**
     * Create an instance of {@link EDReestrInfo }
     * 
     */
    public EDReestrInfo createEDReestrInfo() {
        return new EDReestrInfo();
    }

    /**
     * Create an instance of {@link ESWithMandatoryEDReceiver }
     * 
     */
    public ESWithMandatoryEDReceiver createESWithMandatoryEDReceiver() {
        return new ESWithMandatoryEDReceiver();
    }

    /**
     * Create an instance of {@link ESWithEDSender }
     * 
     */
    public ESWithEDSender createESWithEDSender() {
        return new ESWithEDSender();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link EventTransfer }
     * 
     */
    public EventTransfer createEventTransfer() {
        return new EventTransfer();
    }

    /**
     * Create an instance of {@link FieldInfo }
     * 
     */
    public FieldInfo createFieldInfo() {
        return new FieldInfo();
    }

    /**
     * Create an instance of {@link FinOrg }
     * 
     */
    public FinOrg createFinOrg() {
        return new FinOrg();
    }

    /**
     * Create an instance of {@link FinOrgRU }
     * 
     */
    public FinOrgRU createFinOrgRU() {
        return new FinOrgRU();
    }

    /**
     * Create an instance of {@link GarFundNumber }
     * 
     */
    public GarFundNumber createGarFundNumber() {
        return new GarFundNumber();
    }

    /**
     * Create an instance of {@link GarFunds }
     * 
     */
    public GarFunds createGarFunds() {
        return new GarFunds();
    }

    /**
     * Create an instance of {@link InitialAccDoc }
     * 
     */
    public InitialAccDoc createInitialAccDoc() {
        return new InitialAccDoc();
    }

    /**
     * Create an instance of {@link IndirectParticipantInfoAgType }
     * 
     */
    public IndirectParticipantInfoAgType createIndirectParticipantInfoAgType() {
        return new IndirectParticipantInfoAgType();
    }

    /**
     * Create an instance of {@link IndirectParticipantInfoType }
     * 
     */
    public IndirectParticipantInfoType createIndirectParticipantInfoType() {
        return new IndirectParticipantInfoType();
    }

    /**
     * Create an instance of {@link IntradayRestrictions }
     * 
     */
    public IntradayRestrictions createIntradayRestrictions() {
        return new IntradayRestrictions();
    }

    /**
     * Create an instance of {@link IntradayRestrictionsType }
     * 
     */
    public IntradayRestrictionsType createIntradayRestrictionsType() {
        return new IntradayRestrictionsType();
    }

    /**
     * Create an instance of {@link IPInfo }
     * 
     */
    public IPInfo createIPInfo() {
        return new IPInfo();
    }

    /**
     * Create an instance of {@link IPInfoListType }
     * 
     */
    public IPInfoListType createIPInfoListType() {
        return new IPInfoListType();
    }

    /**
     * Create an instance of {@link IPBICAccListType }
     * 
     */
    public IPBICAccListType createIPBICAccListType() {
        return new IPBICAccListType();
    }

    /**
     * Create an instance of {@link IPListType }
     * 
     */
    public IPListType createIPListType() {
        return new IPListType();
    }

    /**
     * Create an instance of {@link LimitInfoType }
     * 
     */
    public LimitInfoType createLimitInfoType() {
        return new LimitInfoType();
    }

    /**
     * Create an instance of {@link LimitInfoBrfType }
     * 
     */
    public LimitInfoBrfType createLimitInfoBrfType() {
        return new LimitInfoBrfType();
    }

    /**
     * Create an instance of {@link LimitsInfo }
     * 
     */
    public LimitsInfo createLimitsInfo() {
        return new LimitsInfo();
    }

    /**
     * Create an instance of {@link LegacySystemsInfoType }
     * 
     */
    public LegacySystemsInfoType createLegacySystemsInfoType() {
        return new LegacySystemsInfoType();
    }

    /**
     * Create an instance of {@link LimitInfo }
     * 
     */
    public LimitInfo createLimitInfo() {
        return new LimitInfo();
    }

    /**
     * Create an instance of {@link ListAcc }
     * 
     */
    public ListAcc createListAcc() {
        return new ListAcc();
    }

    /**
     * Create an instance of {@link ListAccBrf }
     * 
     */
    public ListAccBrf createListAccBrf() {
        return new ListAccBrf();
    }

    /**
     * Create an instance of {@link ListOfSP }
     * 
     */
    public ListOfSP createListOfSP() {
        return new ListOfSP();
    }

    /**
     * Create an instance of {@link LiquidityReservationSchemeParameters }
     * 
     */
    public LiquidityReservationSchemeParameters createLiquidityReservationSchemeParameters() {
        return new LiquidityReservationSchemeParameters();
    }

    /**
     * Create an instance of {@link Me2MeDetailsType }
     * 
     */
    public Me2MeDetailsType createMe2MeDetailsType() {
        return new Me2MeDetailsType();
    }

    /**
     * Create an instance of {@link Migrated }
     * 
     */
    public Migrated createMigrated() {
        return new Migrated();
    }

    /**
     * Create an instance of {@link OfficialPersonInfo }
     * 
     */
    public OfficialPersonInfo createOfficialPersonInfo() {
        return new OfficialPersonInfo();
    }

    /**
     * Create an instance of {@link PacketEDWithPartInfo }
     * 
     */
    public PacketEDWithPartInfo createPacketEDWithPartInfo() {
        return new PacketEDWithPartInfo();
    }

    /**
     * Create an instance of {@link ParticipantAttributes }
     * 
     */
    public ParticipantAttributes createParticipantAttributes() {
        return new ParticipantAttributes();
    }

    /**
     * Create an instance of {@link RstrListType }
     * 
     */
    public RstrListType createRstrListType() {
        return new RstrListType();
    }

    /**
     * Create an instance of {@link IPRstrListType }
     * 
     */
    public IPRstrListType createIPRstrListType() {
        return new IPRstrListType();
    }

    /**
     * Create an instance of {@link IndirectParticipantAccountType }
     * 
     */
    public IndirectParticipantAccountType createIndirectParticipantAccountType() {
        return new IndirectParticipantAccountType();
    }

    /**
     * Create an instance of {@link DirectParticipantBICAccountType }
     * 
     */
    public DirectParticipantBICAccountType createDirectParticipantBICAccountType() {
        return new DirectParticipantBICAccountType();
    }

    /**
     * Create an instance of {@link AccountStatementListType }
     * 
     */
    public AccountStatementListType createAccountStatementListType() {
        return new AccountStatementListType();
    }

    /**
     * Create an instance of {@link ClearingOrganizationType }
     * 
     */
    public ClearingOrganizationType createClearingOrganizationType() {
        return new ClearingOrganizationType();
    }

    /**
     * Create an instance of {@link ForeignCorrespOrganizationsType }
     * 
     */
    public ForeignCorrespOrganizationsType createForeignCorrespOrganizationsType() {
        return new ForeignCorrespOrganizationsType();
    }

    /**
     * Create an instance of {@link SWBICsList }
     * 
     */
    public SWBICsList createSWBICsList() {
        return new SWBICsList();
    }

    /**
     * Create an instance of {@link ParticipantInfoType }
     * 
     */
    public ParticipantInfoType createParticipantInfoType() {
        return new ParticipantInfoType();
    }

    /**
     * Create an instance of {@link ParticipantProfileType }
     * 
     */
    public ParticipantProfileType createParticipantProfileType() {
        return new ParticipantProfileType();
    }

    /**
     * Create an instance of {@link ParticipantProfileInfoType }
     * 
     */
    public ParticipantProfileInfoType createParticipantProfileInfoType() {
        return new ParticipantProfileInfoType();
    }

    /**
     * Create an instance of {@link PayeeAccInfo }
     * 
     */
    public PayeeAccInfo createPayeeAccInfo() {
        return new PayeeAccInfo();
    }

    /**
     * Create an instance of {@link PayeeInfo }
     * 
     */
    public PayeeInfo createPayeeInfo() {
        return new PayeeInfo();
    }

    /**
     * Create an instance of {@link PayerRU }
     * 
     */
    public PayerRU createPayerRU() {
        return new PayerRU();
    }

    /**
     * Create an instance of {@link PayeeRU }
     * 
     */
    public PayeeRU createPayeeRU() {
        return new PayeeRU();
    }

    /**
     * Create an instance of {@link FreeServicesCodeList }
     * 
     */
    public FreeServicesCodeList createFreeServicesCodeList() {
        return new FreeServicesCodeList();
    }

    /**
     * Create an instance of {@link PayServicesCodeList }
     * 
     */
    public PayServicesCodeList createPayServicesCodeList() {
        return new PayServicesCodeList();
    }

    /**
     * Create an instance of {@link PayServicesList }
     * 
     */
    public PayServicesList createPayServicesList() {
        return new PayServicesList();
    }

    /**
     * Create an instance of {@link PendingDeletionInfo }
     * 
     */
    public PendingDeletionInfo createPendingDeletionInfo() {
        return new PendingDeletionInfo();
    }

    /**
     * Create an instance of {@link PoolSPInfo }
     * 
     */
    public PoolSPInfo createPoolSPInfo() {
        return new PoolSPInfo();
    }

    /**
     * Create an instance of {@link ProcessingDetails }
     * 
     */
    public ProcessingDetails createProcessingDetails() {
        return new ProcessingDetails();
    }

    /**
     * Create an instance of {@link RCPSchemeParameters }
     * 
     */
    public RCPSchemeParameters createRCPSchemeParameters() {
        return new RCPSchemeParameters();
    }

    /**
     * Create an instance of {@link RelatedDocRefID }
     * 
     */
    public RelatedDocRefID createRelatedDocRefID() {
        return new RelatedDocRefID();
    }

    /**
     * Create an instance of {@link RestrictionBasisDocument }
     * 
     */
    public RestrictionBasisDocument createRestrictionBasisDocument() {
        return new RestrictionBasisDocument();
    }

    /**
     * Create an instance of {@link ReservationInfo }
     * 
     */
    public ReservationInfo createReservationInfo() {
        return new ReservationInfo();
    }

    /**
     * Create an instance of {@link RTGSCustomerInfo }
     * 
     */
    public RTGSCustomerInfo createRTGSCustomerInfo() {
        return new RTGSCustomerInfo();
    }

    /**
     * Create an instance of {@link SEDAccInfo }
     * 
     */
    public SEDAccInfo createSEDAccInfo() {
        return new SEDAccInfo();
    }

    /**
     * Create an instance of {@link SEDAccDocInfo }
     * 
     */
    public SEDAccDocInfo createSEDAccDocInfo() {
        return new SEDAccDocInfo();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link SettlementCondition }
     * 
     */
    public SettlementCondition createSettlementCondition() {
        return new SettlementCondition();
    }

    /**
     * Create an instance of {@link SettleNotEarlier }
     * 
     */
    public SettleNotEarlier createSettleNotEarlier() {
        return new SettleNotEarlier();
    }

    /**
     * Create an instance of {@link SettleNotLater }
     * 
     */
    public SettleNotLater createSettleNotLater() {
        return new SettleNotLater();
    }

    /**
     * Create an instance of {@link ShortPayeeInfo }
     * 
     */
    public ShortPayeeInfo createShortPayeeInfo() {
        return new ShortPayeeInfo();
    }

    /**
     * Create an instance of {@link SPInfo }
     * 
     */
    public SPInfo createSPInfo() {
        return new SPInfo();
    }

    /**
     * Create an instance of {@link MainPoolParticipant }
     * 
     */
    public MainPoolParticipant createMainPoolParticipant() {
        return new MainPoolParticipant();
    }

    /**
     * Create an instance of {@link BalanceSweepingAccount }
     * 
     */
    public BalanceSweepingAccount createBalanceSweepingAccount() {
        return new BalanceSweepingAccount();
    }

    /**
     * Create an instance of {@link SumWithUnlimit }
     * 
     */
    public SumWithUnlimit createSumWithUnlimit() {
        return new SumWithUnlimit();
    }

    /**
     * Create an instance of {@link SumWithUnlimitAndInd }
     * 
     */
    public SumWithUnlimitAndInd createSumWithUnlimitAndInd() {
        return new SumWithUnlimitAndInd();
    }

    /**
     * Create an instance of {@link SWBICList }
     * 
     */
    public SWBICList createSWBICList() {
        return new SWBICList();
    }

    /**
     * Create an instance of {@link SWIFTTypeList }
     * 
     */
    public SWIFTTypeList createSWIFTTypeList() {
        return new SWIFTTypeList();
    }

    /**
     * Create an instance of {@link SWIFTMXTypeList }
     * 
     */
    public SWIFTMXTypeList createSWIFTMXTypeList() {
        return new SWIFTMXTypeList();
    }

    /**
     * Create an instance of {@link TSLCTypeList }
     * 
     */
    public TSLCTypeList createTSLCTypeList() {
        return new TSLCTypeList();
    }

    /**
     * Create an instance of {@link ISOTypeList }
     * 
     */
    public ISOTypeList createISOTypeList() {
        return new ISOTypeList();
    }

    /**
     * Create an instance of {@link ISOTSTypeList }
     * 
     */
    public ISOTSTypeList createISOTSTypeList() {
        return new ISOTSTypeList();
    }

    /**
     * Create an instance of {@link ISOCTCCRTypeList }
     * 
     */
    public ISOCTCCRTypeList createISOCTCCRTypeList() {
        return new ISOCTCCRTypeList();
    }

    /**
     * Create an instance of {@link TUCodeList }
     * 
     */
    public TUCodeList createTUCodeList() {
        return new TUCodeList();
    }

    /**
     * Create an instance of {@link UFCFInfo }
     * 
     */
    public UFCFInfo createUFCFInfo() {
        return new UFCFInfo();
    }

    /**
     * Create an instance of {@link UFCFRecord }
     * 
     */
    public UFCFRecord createUFCFRecord() {
        return new UFCFRecord();
    }

    /**
     * Create an instance of {@link UFCFMD }
     * 
     */
    public UFCFMD createUFCFMD() {
        return new UFCFMD();
    }

    /**
     * Create an instance of {@link OpPreciousMetal }
     * 
     */
    public OpPreciousMetal createOpPreciousMetal() {
        return new OpPreciousMetal();
    }

    /**
     * Create an instance of {@link OpRevaluationInfo }
     * 
     */
    public OpRevaluationInfo createOpRevaluationInfo() {
        return new OpRevaluationInfo();
    }

    /**
     * Create an instance of {@link InitialEDInfo }
     * 
     */
    public InitialEDInfo createInitialEDInfo() {
        return new InitialEDInfo();
    }

    /**
     * Create an instance of {@link ESIDResponse }
     * 
     */
    public ESIDResponse createESIDResponse() {
        return new ESIDResponse();
    }

    /**
     * Create an instance of {@link BRCashType }
     * 
     */
    public BRCashType createBRCashType() {
        return new BRCashType();
    }

    /**
     * Create an instance of {@link BICAccount }
     * 
     */
    public BICAccount createBICAccount() {
        return new BICAccount();
    }

    /**
     * Create an instance of {@link BankFPSED }
     * 
     */
    public BankFPSED createBankFPSED() {
        return new BankFPSED();
    }

    /**
     * Create an instance of {@link RequestInfoType }
     * 
     */
    public RequestInfoType createRequestInfoType() {
        return new RequestInfoType();
    }

    /**
     * Create an instance of {@link DateTimeInterval }
     * 
     */
    public DateTimeInterval createDateTimeInterval() {
        return new DateTimeInterval();
    }

    /**
     * Create an instance of {@link BusinessDay }
     * 
     */
    public BusinessDay createBusinessDay() {
        return new BusinessDay();
    }

    /**
     * Create an instance of {@link FPSRequestInfoType }
     * 
     */
    public FPSRequestInfoType createFPSRequestInfoType() {
        return new FPSRequestInfoType();
    }

    /**
     * Create an instance of {@link BilateralBalanceType }
     * 
     */
    public BilateralBalanceType createBilateralBalanceType() {
        return new BilateralBalanceType();
    }

    /**
     * Create an instance of {@link FPSBilateralBalanceType }
     * 
     */
    public FPSBilateralBalanceType createFPSBilateralBalanceType() {
        return new FPSBilateralBalanceType();
    }

    /**
     * Create an instance of {@link FPSTurnoverType }
     * 
     */
    public FPSTurnoverType createFPSTurnoverType() {
        return new FPSTurnoverType();
    }

    /**
     * Create an instance of {@link TimeFromTo }
     * 
     */
    public TimeFromTo createTimeFromTo() {
        return new TimeFromTo();
    }

    /**
     * Create an instance of {@link TimePeriod }
     * 
     */
    public TimePeriod createTimePeriod() {
        return new TimePeriod();
    }

    /**
     * Create an instance of {@link CustomerFK }
     * 
     */
    public CustomerFK createCustomerFK() {
        return new CustomerFK();
    }

    /**
     * Create an instance of {@link EDWithDeclaration }
     * 
     */
    public EDWithDeclaration createEDWithDeclaration() {
        return new EDWithDeclaration();
    }

    /**
     * Create an instance of {@link InstitutionFK }
     * 
     */
    public InstitutionFK createInstitutionFK() {
        return new InstitutionFK();
    }

    /**
     * Create an instance of {@link BankFK }
     * 
     */
    public BankFK createBankFK() {
        return new BankFK();
    }

    /**
     * Create an instance of {@link ChangeStatusType }
     * 
     */
    public ChangeStatusType createChangeStatusType() {
        return new ChangeStatusType();
    }

    /**
     * Create an instance of {@link StatusInformationType }
     * 
     */
    public StatusInformationType createStatusInformationType() {
        return new StatusInformationType();
    }

    /**
     * Create an instance of {@link SWIFTErrCodeList }
     * 
     */
    public SWIFTErrCodeList createSWIFTErrCodeList() {
        return new SWIFTErrCodeList();
    }

}
