//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Информация о лице.
 * 
 * <p>Java class for OfficialPersonInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfficialPersonInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="HoldPosition" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max150TextType" /&gt;
 *       &lt;attribute name="Name" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max60TextType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfficialPersonInfo")
public class OfficialPersonInfo
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "HoldPosition", required = true)
    protected String holdPosition;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the holdPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoldPosition() {
        return holdPosition;
    }

    /**
     * Sets the value of the holdPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoldPosition(String value) {
        this.holdPosition = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
