//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Список кодов ошибок SWIFT
 * 
 * <p>Java class for SWIFTErrCodeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SWIFTErrCodeList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SWIFTErrAnnotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SWIFTErrCode" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Eq3TextType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SWIFTErrCodeList", propOrder = {
    "swiftErrAnnotation"
})
public class SWIFTErrCodeList
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "SWIFTErrAnnotation")
    protected String swiftErrAnnotation;
    @XmlAttribute(name = "SWIFTErrCode", required = true)
    protected String swiftErrCode;

    /**
     * Gets the value of the swiftErrAnnotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFTErrAnnotation() {
        return swiftErrAnnotation;
    }

    /**
     * Sets the value of the swiftErrAnnotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFTErrAnnotation(String value) {
        this.swiftErrAnnotation = value;
    }

    /**
     * Gets the value of the swiftErrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFTErrCode() {
        return swiftErrCode;
    }

    /**
     * Sets the value of the swiftErrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFTErrCode(String value) {
        this.swiftErrCode = value;
    }

}
