//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.v2;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Список типов сообщений SWIFT MX
 * 
 * <p>Java class for SWIFTMXTypeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SWIFTMXTypeList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="SWIFTMXTypeNo" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max15TextType" fixed="999999999999999" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SWIFTMXTypeList")
public class SWIFTMXTypeList
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "SWIFTMXTypeNo", required = true)
    protected String swiftmxTypeNo;

    /**
     * Gets the value of the swiftmxTypeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFTMXTypeNo() {
        if (swiftmxTypeNo == null) {
            return "999999999999999";
        } else {
            return swiftmxTypeNo;
        }
    }

    /**
     * Sets the value of the swiftmxTypeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFTMXTypeNo(String value) {
        this.swiftmxTypeNo = value;
    }

}
