//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.leaftypes.v2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccRstrCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="AccRstrCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CLRS"/&gt;
 *     &lt;enumeration value="LMRS"/&gt;
 *     &lt;enumeration value="URRS"/&gt;
 *     &lt;enumeration value="PSRS"/&gt;
 *     &lt;enumeration value="ESRS"/&gt;
 *     &lt;enumeration value="SCRS"/&gt;
 *     &lt;enumeration value="MVRS"/&gt;
 *     &lt;enumeration value="RTRS"/&gt;
 *     &lt;enumeration value="FPRS"/&gt;
 *     &lt;enumeration value="LSRS"/&gt;
 *     &lt;enumeration value="QPRS"/&gt;
 *     &lt;enumeration value="FWRS"/&gt;
 *     &lt;enumeration value="SDRS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AccRstrCodeType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum AccRstrCodeType {

    CLRS,
    LMRS,
    URRS,
    PSRS,
    ESRS,
    SCRS,
    MVRS,
    RTRS,
    FPRS,
    LSRS,
    QPRS,
    FWRS,
    SDRS;

    public String value() {
        return name();
    }

    public static AccRstrCodeType fromValue(String v) {
        return valueOf(v);
    }

}
