//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.leaftypes.v2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ED702ChargeBankRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ED702ChargeBankRoleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CH01"/&gt;
 *     &lt;enumeration value="CH02"/&gt;
 *     &lt;enumeration value="CH03"/&gt;
 *     &lt;enumeration value="CH04"/&gt;
 *     &lt;enumeration value="CH05"/&gt;
 *     &lt;enumeration value="CH06"/&gt;
 *     &lt;enumeration value="CH07"/&gt;
 *     &lt;enumeration value="CH08"/&gt;
 *     &lt;enumeration value="CH09"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ED702ChargeBankRoleType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum ED702ChargeBankRoleType {

    @XmlEnumValue("CH01")
    CH_01("CH01"),
    @XmlEnumValue("CH02")
    CH_02("CH02"),
    @XmlEnumValue("CH03")
    CH_03("CH03"),
    @XmlEnumValue("CH04")
    CH_04("CH04"),
    @XmlEnumValue("CH05")
    CH_05("CH05"),
    @XmlEnumValue("CH06")
    CH_06("CH06"),
    @XmlEnumValue("CH07")
    CH_07("CH07"),
    @XmlEnumValue("CH08")
    CH_08("CH08"),
    @XmlEnumValue("CH09")
    CH_09("CH09");
    private final String value;

    ED702ChargeBankRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ED702ChargeBankRoleType fromValue(String v) {
        for (ED702ChargeBankRoleType c: ED702ChargeBankRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
