//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 05:36:11 PM SAMT 
//


package ru.cbr.ed.leaftypes.v2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="OperationTextType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="AAAC"/&gt;
 *     &lt;enumeration value="APAC"/&gt;
 *     &lt;enumeration value="CHNG"/&gt;
 *     &lt;enumeration value="CWAC"/&gt;
 *     &lt;enumeration value="NSRP"/&gt;
 *     &lt;enumeration value="FORE"/&gt;
 *     &lt;enumeration value="OTAE"/&gt;
 *     &lt;enumeration value="OTAP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OperationTextType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum OperationTextType {

    AAAC,
    APAC,
    CHNG,
    CWAC,
    NSRP,
    FORE,
    OTAE,
    OTAP;

    public String value() {
        return name();
    }

    public static OperationTextType fromValue(String v) {
        return valueOf(v);
    }

}
